### ISSUE TITLE
Resources - Up/Down Arrows need to be smaller 

### ISSUE THREAD

**Issue by mkelso00** [lintol/lintol-frontend#46]
These should also be grey.

**Comment by martinnaughton** [comment]
fixed

**Comment by flashharry82** [comment]
this still needs grey colour for .arrowDown and .arrowUp classes

**Comment by philtweir** [comment]
Arrows greyed in incoming PR. The smaller arrows do seem less clear than the InVision ones - did you use an SVG for them, @mkelso00 ?

**Comment by AndrewWalter** [comment]
fixed
