### ISSUE TITLE
Sidebar Footer - CKAN Link

### ISSUE THREAD

**Issue by mkelso00** [lintol/lintol-frontend#56]
Instead of having the url in the bottom left hand corner just have an <a href="{server}">Server URL?</a> So you cna hover and see but it does not go onto multiple lines.

**Comment by philtweir** [comment]
How's that now, @mkelso00? We have a "via XYZ" where XYZ is CKAN or GITHUB and links to the server landing page (github.com / CKAN's).

**Comment by AndrewWalter** [comment]
Functionality removed
