### ISSUE TITLE
Sign in - CKAN button goes outside container box

### ISSUE THREAD

**Issue by flashharry82** [lintol/lintol-frontend#65]
When you click on the "Sign in with CKAN" button, the dropdown for the CKAN server appears but the containing white box doesn't expand so the the button gets pushed outside it. Also the button changes size which seems odd.

![screen shot 2018-03-13 at 18 13 53](https://user-images.githubusercontent.com/954531/37361350-977a8c20-26ea-11e8-95d0-40b3994237f8.png)

**Comment by martinnaughton** [comment]
fixed pushed to master

**Comment by flashharry82** [comment]
It would probably be good if the 'Sign in with CKAN' button didn't change size after being clicked.
