### ISSUE TITLE
Sign in - Login doesn't auto login after CKAN authorisation

### ISSUE THREAD

**Issue by flashharry82** [lintol/lintol-frontend#66]
Once you have authorised through CKAN it redirects back to Lintol but redirects to the sign in page again instead of to the main interface. Clicking 'Sign in using CKAN' then goes to main interface but this shouldn't be required.

**Comment by philtweir** [comment]
Now appears to work - perhaps worth double-checking in case it's a browser issue or on old infrastructure?

**Comment by flashharry82** [comment]
This seems to be fine now although new issue has appeared. See #104
