### ISSUE TITLE
Add Data Profile - styling

### ISSUE THREAD

**Issue by flashharry82** [lintol/lintol-frontend#71]
Name input needs some top and bottom padding

Input borders are different colours and are much darker than the designs

The 'Search for a Processor' input has a magnifying glass in the design. Would this be easy to add? It would probably help indicate that this box can also be typed in.

Orange buttons seem to have drop shadows but designs don't and border-radius is too high

Added processor areas have a slightly grey background in the design.

Radio button orange circle doesn't line up in the centre

Edit Configuration should probably be no wrap.

Delete 'X' is pushed outside border area on smaller resolution screens

Font size of body text, input text and button text should all be the same size

![screen shot 2018-03-13 at 18 46 29](https://user-images.githubusercontent.com/954531/37363044-e0af41ca-26ee-11e8-95fd-da47c2e52664.png)

**Comment by philtweir** [comment]
I'm inclined to think that re-style a Bootstrap 4 Card would be a good starter here -- it'd get the X in the right place, and if we're happy with Edit Configuration at the bottom right, that'd work in too. @martinnaughton any thoughts?

**Comment by AndrewWalter** [comment]
this looks like it has been fixed
