### ISSUE TITLE
Data Profile - Name and description

### ISSUE THREAD

**Issue by flashharry82** [lintol/lintol-frontend#73]
The name and description of a data profile either need restricted in length or truncated for the directory view. Also there should be a bit of padding on the left hand side of the separator line.

![screen shot 2018-03-13 at 19 10 19](https://user-images.githubusercontent.com/954531/37364405-59ae8a1a-26f2-11e8-9880-88af5e48b293.png)

**Comment by martinnaughton** [comment]
limited to 200 characters.

**Comment by flashharry82** [comment]
padding still missing

**Comment by AndrewWalter** [comment]
It looks to me like this has been fixed
