### ISSUE TITLE
Resources - styling

### ISSUE THREAD

**Issue by flashharry82** [lintol/lintol-frontend#77]
Filter inputs need to be at least wide enough for watermark text

![screen shot 2018-03-13 at 19 25 20](https://user-images.githubusercontent.com/954531/37365567-ccbf1878-26f5-11e8-85ed-9dc6b85d143f.png)

Column headers don't line up with content
![screen shot 2018-03-13 at 19 27 38](https://user-images.githubusercontent.com/954531/37365588-def447b6-26f5-11e8-90aa-c31afa60bf78.png)
![screen shot 2018-03-13 at 19 27 53](https://user-images.githubusercontent.com/954531/37365596-e2c84914-26f5-11e8-9aa1-de28ecc876ff.png)

Status indicators  and buttons don't line up
![screen shot 2018-03-13 at 19 28 05](https://user-images.githubusercontent.com/954531/37365641-fb975a02-26f5-11e8-8dab-814fc09adf89.png)

Content cells need padding for when columns get pushed closer together
![screen shot 2018-03-13 at 19 28 15](https://user-images.githubusercontent.com/954531/37365671-11ec14b4-26f6-11e8-8c87-3c1a68a0de10.png)

**Comment by flashharry82** [comment]
Also, the 'View Resource' button has a hover shadow. Should this be removed?

**Comment by martinnaughton** [comment]
fixed, even remove the shadow. I like shadows but not for everyone
