### ISSUE TITLE
File not pulling through from CKAN

### ISSUE THREAD

**Issue by flashharry82** [lintol/lintol-frontend#90]
Tried adding a file in both an existing dataset 'pubtest' and a new dataset 'PII test data'. Both public datasets. File nothing pulled into Lintol resource list.

**Comment by philtweir** [comment]
That should be it now - may have been an issue to do with created_at dates. I can see your `file.csv`

**Comment by flashharry82** [comment]
Just tested with new dataset and upload and works fine

**Comment by flashharry82** [comment]
Not working again.

**Comment by philtweir** [comment]
There was an infrastructure switchover, so this should be back to normal

**Comment by flashharry82** [comment]
Completely new issue see #107
