### ISSUE TITLE
Menu - Validation report button alignment

### ISSUE THREAD

**Issue by flashharry82** [lintol/lintol-frontend#97]
The validation report button is pushing the text onto a new line. Probably needs white-space:nowrap;

![screen shot 2018-06-01 at 15 41 17](https://user-images.githubusercontent.com/954531/40846739-5df7ebd0-65b2-11e8-8e9f-5a3ba16294e2.png)

**Comment by martinnaughton** [comment]
what size is your screen? I can not even reproduce this on a 800 width

**Comment by flashharry82** [comment]
This seems to be fine now.
